"use strict";

systemDictionary = {
  "en": {
    "GitHub Repository URL": "GitHub Repository URL",
    "GitHub Personal Access Token": "GitHub Personal Access Token",
    "Local Script Path": "Local Script Path",
    "Sync Interval (seconds)": "Sync Interval (seconds)",
    "Auto Sync": "Auto Sync",
    "Pull Before Push": "Pull Before Push",
    "Include Path Pattern": "Include Path Pattern",
    "Exclude Path Pattern": "Exclude Path Pattern",
    "GitHub Configuration": "GitHub Configuration",
    "Local Configuration": "Local Configuration",
    "Sync Settings": "Sync Settings",
    "Advanced File Patterns": "Advanced File Patterns",
    "Main": "Main",
    "Advanced": "Advanced",
    "Auto-detected from JavaScript adapter": "Auto-detected from JavaScript adapter",
    "Leave empty to auto-detect from JavaScript adapter configuration. If empty, default path will be used.": "Leave empty to auto-detect from JavaScript adapter configuration. If empty, default path will be used.",
  },
  "de": {
    "GitHub Repository URL": "GitHub-Repository-URL",
    "GitHub Personal Access Token": "Persönliches GitHub-Zugriffstoken",
    "Local Script Path": "Lokaler Skriptpfad",
    "Sync Interval (seconds)": "Sync-Intervall (Sekunden)",
    "Auto Sync": "Automatische Synchronisierung",
    "Pull Before Push": "Vor dem Hochladen herunterladen",
    "Include Path Pattern": "Pfadmuster einschließen",
    "Exclude Path Pattern": "Pfadmuster ausschließen",
    "GitHub Configuration": "GitHub-Konfiguration",
    "Local Configuration": "Lokale Konfiguration",
    "Sync Settings": "Sync-Einstellungen",
    "Advanced File Patterns": "Erweiterte Dateimuster",
    "Main": "Haupt",
    "Advanced": "Fortgeschrittene",
    "Auto-detected from JavaScript adapter": "Automatisch erkannt von JavaScript-Adapter",
    "Leave empty to auto-detect from JavaScript adapter configuration. If empty, default path will be used.": "Leer lassen, um automatisch von der JavaScript-Adapter-Konfiguration zu erkennen. Wenn leer, wird der Standardpfad verwendet.",
  },
  "ru": {
    "GitHub Repository URL": "URL хранилища GitHub",
    "GitHub Personal Access Token": "Персональный токен доступа GitHub",
    "Local Script Path": "Локальный путь скрипта",
    "Sync Interval (seconds)": "Интервал синхронизации (секунды)",
    "Auto Sync": "Автосинхронизация",
    "Pull Before Push": "Загрузить перед отправкой",
    "Include Path Pattern": "Включить шаблон пути",
    "Exclude Path Pattern": "Исключить шаблон пути",
    "GitHub Configuration": "Конфигурация GitHub",
    "Local Configuration": "Локальная конфигурация",
    "Sync Settings": "Параметры синхронизации",
    "Advanced File Patterns": "Расширенные шаблоны файлов",
    "Main": "Основное",
    "Advanced": "Продвинутые",
    "Auto-detected from JavaScript adapter": "Автоматически обнаружено из адаптера JavaScript",
    "Leave empty to auto-detect from JavaScript adapter configuration. If empty, default path will be used.": "Оставьте пустым для автоматического обнаружения из конфигурации адаптера JavaScript. Если пусто, будет использован путь по умолчанию.",
  },
};
